### ISSUE TITLE
Dataset Update

### ISSUE THREAD

**Issue by jimbalaya71** [CriteraGroup/cgapp#14]
1) Update data set to the version sent via email.  

2) These added columns should be drop-down selections.  See tab 2 in spreadsheet for values:
- policy defined  
- control implemented  
- control automated or technically enforced 
- control reported to business

3)  Status Column should be a percentage value based on values entered into the 4 drop-down selections.
4) Drop-down values of 'Not Applicable' should not factor into the status column

**Comment by folterung** [comment]
Requirements have been satisfied.
